# -*- coding: utf-8 -*-
"""simoncode-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-VzP0R3K1MmYOLK4GyE9S-WH_WzRikP
"""

import random
import time

import streamlit as st

# ----------------------------------------------------------------------------
# Page setup
# ----------------------------------------------------------------------------
st.set_page_config(page_title="Who Wants To Be A Millionaire?", page_icon="💰", layout="centered")

LETTERS = ["A", "B", "C", "D"]

# ----------------------------------------------------------------------------
# Prize money ladder (index 0 = nothing won yet, index N = prize for question N)
# ----------------------------------------------------------------------------
PRIZES = [
    0,
    1_000,     2_000,     5_000,
    10_000,    20_000,    50_000,
    100_000,   250_000,   500_000,
    1_000_000, 2_000_000, 5_000_000,
    10_000_000,
]

# One question per prize level. Split across the three difficulty pools.
QUESTIONS_PER_TIER = {"easy": 4, "medium": 5, "hard": 4}  # 4 + 5 + 4 = 13 = len(PRIZES) - 1

# ----------------------------------------------------------------------------
# Questions (easy to read & add to)
# ----------------------------------------------------------------------------
easy_questions = [
    {"question": "What is the square root of 144?", "options": ["10", "11", "12", "14"], "correct": 2},
    {"question": "What is the chemical formula for water?", "options": ["CO₂", "H₂O", "O₂", "NaCl"], "correct": 1},
    {"question": "How many days are in a week?", "options": ["5", "6", "7", "8"], "correct": 2},
    {"question": "Which planet is known as the Red Planet?", "options": ["Venus", "Mars", "Jupiter", "Saturn"], "correct": 1},
    {"question": "What gas do humans breathe in to survive?", "options": ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"], "correct": 2},
    {"question": "Which shape has three sides?", "options": ["Square", "Triangle", "Circle", "Rectangle"], "correct": 1},
    {"question": "What is 5 × 6?", "options": ["11", "25", "30", "35"], "correct": 2},
    {"question": "Which part of the body helps you see?", "options": ["Ear", "Eye", "Nose", "Skin"], "correct": 1},
]

medium_questions = [
    {"question": "Which gas is most abundant in the Earth's atmosphere?", "options": ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], "correct": 2},
    {"question": "Who proposed the theory of evolution by natural selection?", "options": ["Gregor Mendel", "Jean Lamarck", "Charles Darwin", "Louis Pasteur"], "correct": 2},
    {"question": "What type of bond involves sharing of electrons?", "options": ["Ionic", "Covalent", "Metallic", "Hydrogen"], "correct": 1},
    {"question": "What is the capital city of Nigeria?", "options": ["Lagos", "Abuja", "Kano", "Ibadan"], "correct": 1},
    {"question": "Which organ pumps blood around the body?", "options": ["Lungs", "Brain", "Heart", "Kidney"], "correct": 2},
    {"question": "In mathematics, what is the value of π (pi) approximately?", "options": ["2.14", "3.14", "3.41", "4.13"], "correct": 1},
    {"question": "Which Nigerian river is the longest?", "options": ["River Benue", "River Ogun", "River Niger", "River Cross"], "correct": 2},
    {"question": "How many states are there in Nigeria?", "options": ["30", "36", "37", "40"], "correct": 1},
]

hard_questions = [
    {"question": "Which bond has the highest bond dissociation energy?", "options": ["Single bond", "Double bond", "Triple bond", "Hydrogen bond"], "correct": 2},
    {"question": "In what year did Nigeria gain independence?", "options": ["1957", "1960", "1963", "1970"], "correct": 1},
    {"question": "Which scientist formulated the laws of motion?", "options": ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla"], "correct": 2},
    {"question": "What is the SI unit of electric current?", "options": ["Volt", "Ohm", "Ampere", "Watt"], "correct": 2},
    {"question": "Which part of the brain controls balance and coordination?", "options": ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], "correct": 1},
    {"question": "What is the chemical symbol for potassium?", "options": ["P", "Pt", "K", "Po"], "correct": 2},
    {
        "question": "Who was Nigeria’s first Prime Minister?",
        "options": ["Nnamdi Azikiwe", "Obafemi Awolowo", "Abubakar Tafawa Balewa", "Yakubu Gowon"],
        "correct": 2,
    },
    {"question": "Which angle is greater than 90° but less than 180°?", "options": ["Acute", "Right", "Obtuse", "Reflex"], "correct": 2},
]


def build_questions():
    """Shuffle each pool and take the first few from each, easy -> medium -> hard."""
    easy = easy_questions.copy()
    medium = medium_questions.copy()
    hard = hard_questions.copy()
    random.shuffle(easy)
    random.shuffle(medium)
    random.shuffle(hard)

    picked = (
        easy[: QUESTIONS_PER_TIER["easy"]]
        + medium[: QUESTIONS_PER_TIER["medium"]]
        + hard[: QUESTIONS_PER_TIER["hard"]]
    )
    # Never have more questions than prize levels
    return [dict(q) for q in picked[: len(PRIZES) - 1]]


# ----------------------------------------------------------------------------
# Session state
# ----------------------------------------------------------------------------
def init_state():
    defaults = {
        "phase": "setup",          # setup -> playing -> locked -> game_over
        "name": "",
        "questions": [],
        "question_number": 0,
        "money_won": 0,
        "fifty_used": False,
        "audience_used": False,
        "hidden": [],              # option indexes removed by 50:50 on the current question
        "audience": None,          # {option_index: percent} for the current question
        "chosen": None,
        "feedback": "",
        "end_kind": "",            # "wrong", "walk" or "won"
        "end_message": "",
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


def reset_question_state():
    st.session_state.hidden = []
    st.session_state.audience = None
    st.session_state.chosen = None


def start_game(name):
    st.session_state.name = name
    st.session_state.questions = build_questions()
    st.session_state.question_number = 0
    st.session_state.money_won = 0
    st.session_state.fifty_used = False
    st.session_state.audience_used = False
    st.session_state.feedback = ""
    st.session_state.end_kind = ""
    st.session_state.end_message = ""
    reset_question_state()
    st.session_state.phase = "playing"


def current_question():
    return st.session_state.questions[st.session_state.question_number]


# ----------------------------------------------------------------------------
# Actions (used as button callbacks)
# ----------------------------------------------------------------------------
def use_fifty():
    """50:50 - keep the correct answer plus one random wrong answer (this question only)."""
    if st.session_state.fifty_used:
        return
    q = current_question()
    wrong_idxs = [i for i in range(4) if i != q["correct"]]
    keep_wrong = random.choice(wrong_idxs)
    st.session_state.hidden = [i for i in wrong_idxs if i != keep_wrong]
    st.session_state.fifty_used = True


def use_audience():
    """Ask the audience - percentages always add up to 100."""
    if st.session_state.audience_used:
        return
    q = current_question()
    correct = q["correct"]
    visible = [i for i in range(4) if i not in st.session_state.hidden]

    if len(visible) == 2:
        # After 50:50 the audience only chooses between the two remaining answers
        correct_pct = random.randint(60, 85)
        other = [i for i in visible if i != correct][0]
        percents = {correct: correct_pct, other: 100 - correct_pct}
    else:
        correct_vote = random.randint(55, 80)
        wrong_votes = [random.randint(5, 30) for _ in range(3)]
        total = correct_vote + sum(wrong_votes)
        wrong_pcts = [int(v / total * 100) for v in wrong_votes]
        wrong_idxs = [i for i in range(4) if i != correct]
        percents = {correct: 100 - sum(wrong_pcts)}
        for idx, pct in zip(wrong_idxs, wrong_pcts):
            percents[idx] = pct

    st.session_state.audience = percents
    st.session_state.audience_used = True


def lock_answer(option_index):
    st.session_state.chosen = option_index
    st.session_state.phase = "locked"


def walk_away():
    st.session_state.end_kind = "walk"
    st.session_state.end_message = f"You walked away with ₦{st.session_state.money_won:,}"
    st.session_state.phase = "game_over"


def evaluate_answer():
    qn = st.session_state.question_number
    q = current_question()

    if st.session_state.chosen == q["correct"]:
        st.session_state.money_won = PRIZES[qn + 1]
        st.session_state.question_number += 1
        st.session_state.feedback = f"✅ Correct! You now have **₦{st.session_state.money_won:,}**"
        reset_question_state()

        if st.session_state.question_number >= len(st.session_state.questions):
            st.session_state.end_kind = "won"
            st.session_state.end_message = "You answered every question correctly!"
            st.session_state.phase = "game_over"
        else:
            st.session_state.phase = "playing"
    else:
        correct_letter = LETTERS[q["correct"]]
        correct_text = q["options"][q["correct"]]
        st.session_state.end_kind = "wrong"
        st.session_state.end_message = (
            f"❌ Wrong! The correct answer was {correct_letter}) {correct_text}\n\n"
            f"You leave with **₦{st.session_state.money_won:,}**"
        )
        st.session_state.phase = "game_over"


# ----------------------------------------------------------------------------
# UI pieces
# ----------------------------------------------------------------------------
def render_ladder():
    qn = st.session_state.question_number
    lines = []
    for level in range(len(PRIZES) - 1, 0, -1):
        text = f"Q{level} · ₦{PRIZES[level]:,}"
        if level == qn + 1:
            text = f"**▶ {text}**"
        elif level <= qn:
            text = f"✅ {text}"
        lines.append(f"- {text}")
    st.sidebar.markdown("### Prize ladder\n" + "\n".join(lines))
    st.sidebar.markdown(f"**Current winnings:** ₦{st.session_state.money_won:,}")


def render_question(locked):
    qn = st.session_state.question_number
    q = current_question()

    st.markdown(f"**Question {qn + 1}**  –  You can win **₦{PRIZES[qn + 1]:,}**")
    st.markdown(f"### {q['question']}")

    for i in range(4):
        if i in st.session_state.hidden:
            st.button("───", key=f"opt_{qn}_{i}", disabled=True, use_container_width=True)
        else:
            label = f"{LETTERS[i]}) {q['options'][i]}"
            if locked and st.session_state.chosen == i:
                label = "🔒 " + label
            st.button(
                label,
                key=f"opt_{qn}_{i}",
                disabled=locked,
                on_click=lock_answer,
                args=(i,),
                use_container_width=True,
            )

    if st.session_state.audience:
        st.markdown("**Audience says...**")
        rows = [
            f"{LETTERS[i]} → {st.session_state.audience[i]}%"
            for i in range(4)
            if i in st.session_state.audience and i not in st.session_state.hidden
        ]
        st.markdown("\n\n".join(rows))

    lifelines = []
    if not st.session_state.fifty_used:
        lifelines.append("50:50")
    if not st.session_state.audience_used:
        lifelines.append("Audience")
    if lifelines:
        st.caption("Lifelines left: " + " ".join(lifelines))

    col1, col2, col3 = st.columns(3)
    col1.button(
        "50:50",
        key="btn_fifty",
        disabled=locked or st.session_state.fifty_used,
        on_click=use_fifty,
        use_container_width=True,
    )
    col2.button(
        "Ask the Audience",
        key="btn_audience",
        disabled=locked or st.session_state.audience_used,
        on_click=use_audience,
        use_container_width=True,
    )
    col3.button(
        "Walk away",
        key="btn_walk",
        disabled=locked,
        on_click=walk_away,
        use_container_width=True,
    )


# ----------------------------------------------------------------------------
# Main app
# ----------------------------------------------------------------------------
def main():
    init_state()

    st.title("💰 Who Wants To Be A Millionaire?")
    st.caption("Python version – Easy mode")

    phase = st.session_state.phase

    # --- Setup phase ---
    if phase == "setup":
        st.write("Hi! Today you can become a millionaire... in play money 😄")
        name = st.text_input("What is your name?")
        if st.button("Start Game", type="primary"):
            start_game(name.strip() or "Player")
            st.rerun()

    # --- Playing phase ---
    elif phase == "playing":
        render_ladder()
        st.write(f"Welcome **{st.session_state.name}**! Let's play!")
        if st.session_state.feedback:
            st.success(st.session_state.feedback)
            st.session_state.feedback = ""
        render_question(locked=False)

    # --- Answer locked in ---
    elif phase == "locked":
        render_ladder()
        st.write(f"Welcome **{st.session_state.name}**! Let's play!")
        render_question(locked=True)
        st.info("Final answer locking in...")
        time.sleep(2)
        evaluate_answer()
        st.rerun()

    # --- Game over ---
    elif phase == "game_over":
        money = st.session_state.money_won
        kind = st.session_state.end_kind

        if kind == "wrong":
            st.error(st.session_state.end_message)
        elif kind == "won":
            st.success(st.session_state.end_message)
        else:
            st.info(st.session_state.end_message)

        st.divider()
        st.subheader(f"Game finished, {st.session_state.name}!")
        st.markdown(f"You won: **₦{money:,}** 🎉")

        if money >= 1_000_000:
            st.success("MILLIONAIRE!!! 🤑🏆")
        elif money > 0:
            st.write("Great job! You earned some money 😊")
        else:
            st.write("Never mind... try again! You'll do better next time 💪")

        st.button(
            "Play Again",
            type="primary",
            on_click=start_game,
            args=(st.session_state.name,),
        )


main()